---
- import_playbook: playbooks/common.yml
  tags: common
  vars:
    perform_full_upgrade: yes
    install_common_tools: yes

- name: five setup
  hosts: five
  become: true

  tasks:
    - { import_tasks: tasks/security/main.yml, tags: security }
