---
- name: Install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present

- name: Enable unattended-upgrades service
  ansible.builtin.service:
    name: unattended-upgrades
    state: started
    enabled: true
