---
- name: Install basic stuff and utilities
  hosts: all
  become: yes

  vars:
    perform_full_upgrade: no
    install_common_tools: yes

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Full system upgrade
      apt:
        upgrade: full
      when: perform_full_upgrade

  tasks:
    - name: Install some utilities and command line tools
      apt:
        name:
          - curl
          - fd-find
          - git
          - htop
          - jq
          - lsd
          - lshw
          - lsof
          - ncdu
          - python3
          - tcpdump
          - tree
          - unzip
          - vim
        state: present
      when: install_common_tools
